// AUTO-GENERATED by emit-sdk — do not edit.
// Source: plugin.json `action_types`. Run: just gen-plugins

package main

// LaunchParams is the params shape for action "system.launch (Launch App)".
type LaunchParams struct {
	BundleID string `json:"bundle_id"`
	NewInstance *bool `json:"new_instance,omitempty"`
}

// MuteParams is the params shape for action "system.mute (Mute)".
type MuteParams struct {
}

// OpenParams is the params shape for action "system.open (Open URL or File)".
type OpenParams struct {
	Target string `json:"target"`
}

// SetInputParams is the params shape for action "system.set_input (Set Audio Input Device)".
type SetInputParams struct {
	Name string `json:"name"`
}

// SetOutputParams is the params shape for action "system.set_output (Set Audio Output Device)".
type SetOutputParams struct {
	Name string `json:"name"`
}

// UnmuteParams is the params shape for action "system.unmute (Unmute)".
type UnmuteParams struct {
}

// VolumeDownParams is the params shape for action "system.volume_down (Volume Down)".
type VolumeDownParams struct {
}

// VolumeUpParams is the params shape for action "system.volume_up (Volume Up)".
type VolumeUpParams struct {
}

